AsEphemeral defaults as true
Aiko-IT-Systems/DisCatSharp pull request #112
Opened 2022-01-27 02:42 UTC by JBraunsmaJr

# Description

Since the ephemeral boolean is defaulted to false
AsEphemeral should default to true

2022-01-27 02:43 UTC, Lulalaby requested changes

2022-01-27 02:43 UTC, Lulalaby commented on DisCatSharp/Entities/Interaction/DiscordInteractionResponseBuilder.cs
>  		/// <param name="ephemeral">Ephemeral.</param>
```suggestion
		/// <param name="ephemeral">Whether the response should be ephemeral. Defaults to true.param>
```

2022-01-27 03:40 UTC, Lulalaby approved these changes

2022-02-01 08:28 UTC, Lulalaby commented on DisCatSharp/Entities/Interaction/DiscordInteractionResponseBuilder.cs
> +		/// <param name="ephemeral">Whether the response should be ephemeral. Defaults to true.param>
```suggestion
		/// <param name="ephemeral">Whether the response should be ephemeral. Defaults to true.<param>
```

2022-02-01 08:29 UTC, Lulalaby commented on DisCatSharp/Entities/Interaction/DiscordInteractionResponseBuilder.cs
> +		/// <param name="ephemeral">Whether the response should be ephemeral. Defaults to true.<param>
```suggestion
		/// <param name="ephemeral">Whether the response should be ephemeral. Defaults to true.</param>
```

2022-02-01 08:29 UTC, Lulalaby approved these changes

2022-02-01 08:29 UTC, cking approved these changes

2022-02-01 08:41 UTC, merged