Automod implementation
Aiko-IT-Systems/DisCatSharp pull request #224
Opened 2022-11-02 11:10 UTC by xMaxximum

# Description

Tried to implement auto mod

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

@Aiko-IT-Systems/discatsharp

2022-11-02 12:06 UTC, Lulalaby requested changes
Feedback goes brr

2022-11-02 12:06 UTC, Lulalaby commented on DisCatSharp/Clients/DiscordClient.Dispatch.cs
> +			// TODO: Hook dispatch
Dispatch needs to be hooked. Rn the client doesn't fire this events

2022-11-02 12:06 UTC, Lulalaby commented on DisCatSharp/Clients/DiscordClient.Events.cs
> +	#region Automod
Good job, sharded client needs this too, look at old commits for ref

2022-11-02 12:06 UTC, Lulalaby commented on DisCatSharp/Net/Abstractions/Rest/RestAutomodRuleModifyPayload.cs
> +		public Optional<IEnumerable<AutomodAction>> Actions { get; set; }
Use IEnumerable for payloads, it's safer

2022-11-02 12:06 UTC, Lulalaby commented on DisCatSharp/Net/Rest/DiscordApiClient.cs
> +	internal async Task<AutomodRule> CreateAutomodRuleAsync(ulong guildId, string name, AutomodEventType eventType, AutomodTriggerType triggerType, IEnumerable<AutomodAction> actions,
Removed the duplicate and used RestAutomodRuleModifyPayload

2022-11-02 12:06 UTC, Lulalaby commented on DisCatSharp/Net/Rest/DiscordApiClient.cs
> +	internal async Task<DiscordStageInstance> CreateStageInstanceAsync(ulong channelId, string topic, bool sendStartNotification, StagePrivacyLevel privacyLevel = StagePrivacyLevel.GuildOnly, string rea
Ignore that

2022-11-02 12:06 UTC, Lulalaby commented on DisCatSharp/Entities/Guild/DiscordGuild.AuditLog.cs
> +			ac = alr.Entries.Count;
Ignore that

2022-11-02 12:09 UTC, Lulalaby commented
Not sure rn, did you added audit log reason to the api client?

2022-11-02 12:10 UTC, Lulalaby commented
TODO: Implement functions to DiscordGuild

2022-11-02 13:23 UTC, xMaxximum commented
> Not sure rn, did you added audit log reason to the api client?

Nope i don't think so

2022-11-02 13:28 UTC, Lulalaby commented
> > Not sure rn, did you added audit log reason to the api client?
> 
> 
> 
> Nope i don't think so

Then add to all api methods _string reason = null_ and grab the audit log header method from another call.

2022-11-02 16:12 UTC, Lulalaby requested changes

2022-11-02 16:12 UTC, Lulalaby commented on DisCatSharp/Clients/DiscordClient.Dispatch.cs
> +			Channel = channel,
channel might be absent as well.
i.e. when raid

2022-11-02 16:12 UTC, Lulalaby commented on DisCatSharp/Entities/Guild/DiscordGuild.cs
> +		=> this.Discord.ApiClient.GetAutomodRulesAsync(guildId);
```suggestion
	public Task<ReadOnlyCollection<AutomodRule>> GetAutomodRulesAsync()
		=> this.Discord.ApiClient.GetAutomodRulesAsync(this.Id);
```

2022-11-02 16:12 UTC, Lulalaby commented on DisCatSharp/Entities/Guild/DiscordGuild.cs
> +		=> this.Discord.ApiClient.GetAutomodRuleAsync(guildId, ruleId);
```suggestion
	public Task<AutomodRule> GetAutomodRuleAsync(ulong ruleId)
		=> this.Discord.ApiClient.GetAutomodRuleAsync(this.Id, ruleId);
```

2022-11-02 16:12 UTC, Lulalaby commented on DisCatSharp/Entities/Guild/DiscordGuild.cs
> +		=> this.Discord.ApiClient.CreateAutomodRuleAsync(guildId, name, eventType, triggerType, actions, triggerMetadata, enabled, exemptRoles, exemptChannels, reason);
```suggestion
	public Task<AutomodRule> CreateAutomodRuleAsync(string name, AutomodEventType eventType, AutomodTriggerType triggerType, IEnumerable<AutomodAction> actions,
		AutomodTriggerMetadata triggerMetadata = null, bool enabled = false, IEnumerable<ulong> exemptRoles = null, IEnumerable<ulong> exemptChannels = null, string reason = null)
		=> this.Discord.ApiClient.CreateAutomodRuleAsync(this.Id, name, eventType, triggerType, actions, triggerMetadata, enabled, exemptRoles, exemptChannels, reason);
```

2022-11-02 16:12 UTC, Lulalaby commented on DisCatSharp/Entities/Guild/DiscordGuild.cs
> +		=> this.Discord.ApiClient.ModifyAutomodRuleAsync(guildId, ruleId, name, eventType, triggerType, metadata, actions, enabled, exemptRoles, exemptChannels, reason);
```suggestion
	public Task<AutomodRule> ModifyAutomodRuleAsync(ulong ruleId, Optional<string> name, Optional<AutomodEventType> eventType, Optional<AutomodTriggerType> triggerType,
		Optional<AutomodTriggerMetadata> metadata, Optional<IEnumerable<AutomodAction>> actions, Optional<bool> enabled, Optional<IEnumerable<ulong>> exemptRoles,
		Optional<IEnumerable<ulong>> exemptChannels, string reason = null)
		=> this.Discord.ApiClient.ModifyAutomodRuleAsync(this.Id, ruleId, name, eventType, triggerType, metadata, actions, enabled, exemptRoles, exemptChannels, reason);
```

2022-11-02 16:12 UTC, Lulalaby commented on DisCatSharp/Entities/Guild/DiscordGuild.cs
> +		=> this.Discord.ApiClient.DeleteAutomodRuleAsync(guildId, ruleId, reason);
```suggestion
	public Task<AutomodRule> DeleteAutomodRuleAsync(ulong ruleId, string reason = null)
		=> this.Discord.ApiClient.DeleteAutomodRuleAsync(this.Id, ruleId, reason);
```

2022-11-02 16:12 UTC, Lulalaby commented on DisCatSharp/EventArgs/Guild/Automod/AutomodActionExecutedEventArgs.cs
> +		public DiscordChannel? Channel { get; internal set; }
Add channel id too as fallback if the channel wasn't found in cache

2022-11-02 16:12 UTC, Lulalaby commented on DisCatSharp/Net/Rest/DiscordApiClient.cs
> +	internal async Task<AutomodRule> ModifyAutomodRuleAsync(ulong guildId, ulong ruleId, Optional<string> name, Optional<AutomodEventType> eventType, Optional<AutomodTriggerType> triggerType,Optional<Au
```suggestion
	internal async Task<AutomodRule> ModifyAutomodRuleAsync(ulong guildId, ulong ruleId, Optional<string> name, Optional<AutomodEventType> eventType, Optional<AutomodTriggerType> triggerType, Optional<AutomodTriggerMetadata> metadata, Optional<IEnumerable<AutomodAction>> actions,
```

2022-11-03 10:01 UTC, Lulalaby commented on DisCatSharp/Enums/DiscordEvent.cs
> +public enum DiscordEvent : long
```suggestion
public enum DiscordEvent
```

2022-11-03 10:05 UTC, Lulalaby submitted a review, later dismissed

2022-11-03 15:36 UTC, Lulalaby commented on DisCatSharp/Entities/Guild/Automod/AutomodAction.cs
> +		public AutomodAction() { }
```suggestion
		internal AutomodAction() { }
```

2022-11-03 15:37 UTC, Lulalaby commented on DisCatSharp/Entities/Guild/Automod/AutomodTriggerMetadata.cs
> +		public ReadOnlyCollection<string>? AllowList { get; set; }
```suggestion
		public List<string>? AllowList { get; set; }
```
set must be list then

2022-11-03 23:19 UTC, JBraunsmaJr approved these changes
LGTM after the suggestions are implemented

2022-11-05 16:46 UTC, Lulalaby commented on DisCatSharp/Entities/Guild/Automod/AutomodRule.cs
> +		/// Modifies this.GuildId, this.Id auto mod rule.
```suggestion
		/// Modifies this auto mod rule.
```

2022-11-05 16:47 UTC, Lulalaby approved these changes

2022-11-05 16:49 UTC, merged